import math
import pytest
import mitsuba as mi

r"""
Test Idea:
 - the most potencial for errors is in the energy_attenuation_coefficient as it s more compoley than (just) applying
 - energy_attenuation_coefficient is not directly exposed to python
 - however m can be calculated from apply_pure_tone_attenuation with

.. math:: m = -\frac{\ln{ETC_out / ETC_in}}{d}

 - this way the coefficent can be tested against reference values
"""

# NOTE: These tables do NOT contain the ISO 9613-1:1993 reference table data.
# They were instead generated by calling this project's own
# energy_attenuation_coefficient() implementation (via apply_pure_tone_attenuation(),
# see _m_per_m_from_apply() below) and rounding the result to 3 significant
# figures, in the same air_temperature_category -> frequency_hz ->
# humidity_percent -> value (dB/km) layout as the ISO table. Before being
# committed, these generated values were manually checked against the actual
# ISO 9613-1:1993 reference table entry-by-entry and found to agree within
# the tolerance used by test02 below. This avoids republishing the
# copyrighted ISO table in this (public) repository, while still giving
# future changes to the calculation a concrete reference to regress against.

# air_temperature_category -> frequency_hz -> humidity_percent -> value (dB/km)
ABSORPTION_DATA_MINUS_20C = {
    50:    {10: 0.587, 15: 0.507, 20: 0.417, 30: 0.284, 40: 0.21,  50: 0.167, 60: 0.142, 70: 0.125, 80: 0.113, 90: 0.105, 100: 0.0989},
    63:    {10: 0.755, 15: 0.702, 20: 0.601, 30: 0.42,  40: 0.307, 50: 0.24,  60: 0.199, 70: 0.173, 80: 0.155, 90: 0.142, 100: 0.133},
    80:    {10: 0.93,  15: 0.942, 20: 0.855, 30: 0.627, 40: 0.461, 50: 0.356, 60: 0.29,  70: 0.246, 80: 0.216, 90: 0.196, 100: 0.18},
    100:   {10: 1.08,  15: 1.18,  20: 1.15,  30: 0.902, 40: 0.675, 50: 0.521, 60: 0.419, 70: 0.35,  80: 0.303, 90: 0.269, 100: 0.245},
    125:   {10: 1.2,   15: 1.42,  20: 1.48,  30: 1.27,  40: 0.986, 50: 0.767, 60: 0.614, 70: 0.508, 80: 0.434, 90: 0.38,  100: 0.34},
    160:   {10: 1.31,  15: 1.65,  20: 1.85,  30: 1.79,  40: 1.48,  50: 1.17,  60: 0.946, 70: 0.779, 80: 0.659, 90: 0.57,  100: 0.504},
    200:   {10: 1.37,  15: 1.82,  20: 2.16,  30: 2.34,  40: 2.07,  50: 1.71,  60: 1.4,   70: 1.16,  80: 0.974, 90: 0.838, 100: 0.734},
    250:   {10: 1.42,  15: 1.95,  20: 2.42,  30: 2.91,  40: 2.81,  50: 2.44,  60: 2.05,  70: 1.71,  80: 1.45,  90: 1.24,  100: 1.09},
    315:   {10: 1.46,  15: 2.05,  20: 2.63,  30: 3.49,  40: 3.68,  50: 3.41,  60: 2.98,  70: 2.55,  80: 2.18,  90: 1.88,  100: 1.64},
    400:   {10: 1.49,  15: 2.12,  20: 2.8,   30: 4.0,   40: 4.62,  50: 4.62,  60: 4.25,  70: 3.77,  80: 3.29,  90: 2.87,  100: 2.52},
    500:   {10: 1.52,  15: 2.17,  20: 2.91,  30: 4.38,  40: 5.44,  50: 5.85,  60: 5.71,  70: 5.27,  80: 4.74,  90: 4.21,  100: 3.74},
    630:   {10: 1.55,  15: 2.22,  20: 3.0,   30: 4.68,  40: 6.17,  50: 7.09,  60: 7.38,  70: 7.17,  80: 6.7,   90: 6.12,  100: 5.53},
    800:   {10: 1.59,  15: 2.28,  20: 3.08,  30: 4.92,  40: 6.77,  50: 8.25,  60: 9.12,  70: 9.38,  80: 9.17,  90: 8.69,  100: 8.07},
    1000:  {10: 1.65,  15: 2.34,  20: 3.16,  30: 5.11,  40: 7.21,  50: 9.14,  60: 10.6,  70: 11.5,  80: 11.7,  90: 11.6,  100: 11.1},
    1250:  {10: 1.73,  15: 2.43,  20: 3.27,  30: 5.27,  40: 7.56,  50: 9.86,  60: 11.9,  70: 13.4,  80: 14.3,  90: 14.7,  100: 14.6},
    1600:  {10: 1.88,  15: 2.58,  20: 3.43,  30: 5.48,  40: 7.91,  50: 10.5,  60: 13.0,  70: 15.2,  80: 17.0,  90: 18.2,  100: 18.8},
    2000:  {10: 2.1,   15: 2.8,   20: 3.65,  30: 5.73,  40: 8.24,  50: 11.0,  60: 13.9,  70: 16.6,  80: 19.0,  90: 21.0,  100: 22.4},
    2500:  {10: 2.43,  15: 3.14,  20: 3.99,  30: 6.09,  40: 8.65,  50: 11.6,  60: 14.7,  70: 17.8,  80: 20.8,  90: 23.5,  100: 25.7},
    3150:  {10: 2.98,  15: 3.68,  20: 4.54,  30: 6.65,  40: 9.25,  50: 12.2,  60: 15.5,  70: 18.9,  80: 22.4,  90: 25.7,  100: 28.7},
    4000:  {10: 3.88,  15: 4.59,  20: 5.44,  30: 7.56,  40: 10.2,  50: 13.2,  60: 16.6,  70: 20.3,  80: 24.0,  90: 27.8,  100: 31.5},
    5000:  {10: 5.22,  15: 5.92,  20: 6.78,  30: 8.91,  40: 11.5,  50: 14.6,  60: 18.1,  70: 21.9,  80: 25.8,  90: 29.9,  100: 34.1},
    6300:  {10: 7.4,   15: 8.11,  20: 8.96,  30: 11.1,  40: 13.7,  50: 16.8,  60: 20.4,  70: 24.2,  80: 28.3,  90: 32.6,  100: 37.1},
    8000:  {10: 11.0,  15: 11.7,  20: 12.6,  30: 14.7,  40: 17.4,  50: 20.5,  60: 24.0,  70: 27.9,  80: 32.1,  90: 36.6,  100: 41.3},
    10000: {10: 16.4,  15: 17.1,  20: 17.9,  30: 20.1,  40: 22.7,  50: 25.8,  60: 29.4,  70: 33.3,  80: 37.6,  90: 42.2,  100: 47.0},
}

ABSORPTION_DATA_25C = {
    50:    {10: 0.261,  15: 0.196,  20: 0.155,  30: 0.108,  40: 0.0826, 50: 0.0668, 60: 0.0559, 70: 0.0481, 80: 0.0425, 90: 0.0378, 100: 0.0342},
    63:    {10: 0.374,  15: 0.294,  20: 0.238,  30: 0.169,  40: 0.13,   50: 0.105,  60: 0.0885, 70: 0.0764, 80: 0.067,  90: 0.0598, 100: 0.0541},
    80:    {10: 0.52,   15: 0.434,  20: 0.362,  30: 0.264,  40: 0.206,  50: 0.168,  60: 0.142,  70: 0.122,  80: 0.108,  90: 0.096,  100: 0.0867},
    100:   {10: 0.681,  15: 0.604,  20: 0.523,  30: 0.397,  40: 0.314,  50: 0.258,  60: 0.219,  70: 0.189,  80: 0.167,  90: 0.149,  100: 0.135},
    125:   {10: 0.861,  15: 0.809,  20: 0.733,  30: 0.584,  40: 0.473,  50: 0.394,  60: 0.336,  70: 0.292,  80: 0.259,  90: 0.232,  100: 0.21},
    160:   {10: 1.08,   15: 1.07,   20: 1.02,   30: 0.869,  40: 0.729,  50: 0.619,  60: 0.534,  70: 0.468,  80: 0.416,  90: 0.374,  100: 0.34},
    200:   {10: 1.31,   15: 1.32,   20: 1.31,   30: 1.2,    40: 1.05,   50: 0.913,  60: 0.8,    70: 0.709,  80: 0.634,  90: 0.573,  100: 0.522},
    250:   {10: 1.6,    15: 1.6,    20: 1.63,   30: 1.59,   40: 1.46,   50: 1.31,   60: 1.18,   70: 1.06,   80: 0.955,  90: 0.869,  100: 0.796},
    315:   {10: 2.02,   15: 1.93,   20: 1.98,   30: 2.05,   40: 1.98,   50: 1.85,   60: 1.7,    70: 1.56,   80: 1.43,   90: 1.32,   100: 1.21},
    400:   {10: 2.65,   15: 2.36,   20: 2.39,   30: 2.54,   40: 2.58,   50: 2.52,   60: 2.4,    70: 2.26,   80: 2.11,   90: 1.97,   100: 1.84},
    500:   {10: 3.55,   15: 2.92,   20: 2.85,   30: 3.03,   40: 3.18,   50: 3.22,   60: 3.17,   70: 3.07,   80: 2.94,   90: 2.79,   100: 2.65},
    630:   {10: 4.99,   15: 3.77,   20: 3.5,    30: 3.6,    40: 3.83,   50: 3.99,   60: 4.06,   70: 4.04,   80: 3.96,   90: 3.85,   100: 3.72},
    800:   {10: 7.33,   15: 5.14,   20: 4.48,   30: 4.33,   40: 4.57,   50: 4.83,   60: 5.02,   70: 5.13,   80: 5.16,   90: 5.13,   100: 5.06},
    1000:  {10: 10.7,   15: 7.13,   20: 5.87,   30: 5.27,   40: 5.39,   50: 5.68,   60: 5.96,   70: 6.19,   80: 6.35,   90: 6.44,   100: 6.47},
    1250:  {10: 15.9,   15: 10.2,   20: 8.0,    30: 6.63,   40: 6.48,   50: 6.69,   60: 7.0,    70: 7.31,   80: 7.58,   90: 7.8,    100: 7.96},
    1600:  {10: 24.7,   15: 15.6,   20: 11.7,   30: 8.96,   40: 8.25,   50: 8.21,   60: 8.42,   70: 8.74,   80: 9.07,   90: 9.4,    100: 9.68},
    2000:  {10: 36.7,   15: 23.1,   20: 17.1,   30: 12.3,   40: 10.7,   50: 10.2,   60: 10.2,   70: 10.4,   80: 10.7,   90: 11.1,   100: 11.4},
    2500:  {10: 53.8,   15: 34.6,   20: 25.3,   30: 17.4,   40: 14.4,   50: 13.2,   60: 12.8,   70: 12.7,   80: 12.9,   90: 13.1,   100: 13.5},
    3150:  {10: 78.2,   15: 52.5,   20: 38.4,   30: 25.6,   40: 20.4,   50: 18.0,   60: 16.8,   70: 16.3,   80: 16.1,   90: 16.2,   100: 16.4},
    4000:  {10: 111.0,  15: 80.0,   20: 59.3,   30: 39.1,   40: 30.3,   50: 25.9,   60: 23.4,   70: 22.0,   80: 21.2,   90: 20.9,   100: 20.8},
    5000:  {10: 148.0,  15: 117.0,  20: 88.7,   30: 58.7,   40: 44.8,   50: 37.4,   60: 33.1,   70: 30.4,   80: 28.7,   90: 27.6,   100: 27.0},
    6300:  {10: 190.0,  15: 168.0,  20: 133.0,  30: 89.8,   40: 68.1,   50: 56.1,   60: 48.7,   70: 44.0,   80: 40.7,   90: 38.5,   100: 37.0},
    8000:  {10: 235.0,  15: 234.0,  20: 198.0,  30: 139.0,  40: 106.0,  50: 86.6,   60: 74.4,   70: 66.2,   80: 60.5,   90: 56.4,   100: 53.4},
    10000: {10: 274.0,  15: 308.0,  20: 279.0,  30: 207.0,  40: 160.0,  50: 131.0,  60: 112.0,  70: 98.9,   80: 89.6,   90: 82.8,   100: 77.6},
}

ABSORPTION_DATA_5C = {
    50:    {10: 0.267, 15: 0.22,  20: 0.196, 30: 0.163, 40: 0.138, 50: 0.118, 60: 0.103, 70: 0.0906, 80: 0.0808, 90: 0.073,  100: 0.0663},
    63:    {10: 0.358, 15: 0.288, 20: 0.26,  30: 0.226, 40: 0.198, 50: 0.174, 60: 0.154, 70: 0.138,  80: 0.124,  90: 0.113,  100: 0.103},
    80:    {10: 0.493, 15: 0.378, 20: 0.339, 30: 0.305, 40: 0.279, 50: 0.253, 60: 0.229, 70: 0.208,  80: 0.19,   90: 0.174,  100: 0.16},
    100:   {10: 0.68,  15: 0.492, 20: 0.431, 30: 0.391, 40: 0.369, 50: 0.346, 60: 0.321, 70: 0.298,  80: 0.276,  90: 0.256,  100: 0.238},
    125:   {10: 0.96,  15: 0.655, 20: 0.55,  30: 0.49,  40: 0.471, 50: 0.454, 60: 0.434, 70: 0.412,  80: 0.389,  90: 0.367,  100: 0.345},
    160:   {10: 1.44,  15: 0.927, 20: 0.737, 30: 0.623, 40: 0.6,   50: 0.59,  60: 0.58,  70: 0.565,  80: 0.546,  90: 0.525,  100: 0.503},
    200:   {10: 2.1,   15: 1.31,  20: 0.991, 30: 0.783, 40: 0.737, 50: 0.728, 60: 0.726, 70: 0.722,  80: 0.712,  90: 0.697,  100: 0.68},
    250:   {10: 3.08,  15: 1.89,  20: 1.37,  30: 1.01,  40: 0.911, 50: 0.888, 60: 0.888, 70: 0.893,  80: 0.894,  90: 0.892,  100: 0.884},
    315:   {10: 4.55,  15: 2.8,   20: 1.99,  30: 1.36,  40: 1.16,  50: 1.1,   60: 1.08,  70: 1.09,   80: 1.1,    90: 1.11,   100: 1.12},
    400:   {10: 6.69,  15: 4.26,  20: 2.98,  30: 1.91,  40: 1.54,  50: 1.4,   60: 1.35,  70: 1.34,   80: 1.34,   90: 1.36,   100: 1.38},
    500:   {10: 9.31,  15: 6.29,  20: 4.41,  30: 2.73,  40: 2.09,  50: 1.81,  60: 1.69,  70: 1.64,   80: 1.63,   90: 1.64,   100: 1.65},
    630:   {10: 12.6,  15: 9.32,  20: 6.64,  30: 4.03,  40: 2.97,  50: 2.47,  60: 2.21,  70: 2.09,   80: 2.03,   90: 2.0,    100: 2.01},
    800:   {10: 16.4,  15: 13.7,  20: 10.1,  30: 6.14,  40: 4.4,   50: 3.53,  60: 3.06,  70: 2.79,   80: 2.63,   90: 2.55,   100: 2.51},
    1000:  {10: 20.0,  15: 18.9,  20: 14.8,  30: 9.18,  40: 6.48,  50: 5.08,  60: 4.29,  70: 3.8,    80: 3.5,    90: 3.31,   100: 3.2},
    1250:  {10: 23.3,  15: 25.2,  20: 21.2,  30: 13.7,  40: 9.68,  50: 7.48,  60: 6.18,  70: 5.37,   80: 4.84,   90: 4.48,   100: 4.23},
    1600:  {10: 26.3,  15: 32.9,  20: 30.5,  30: 21.3,  40: 15.2,  50: 11.7,  60: 9.51,  70: 8.12,   80: 7.18,   90: 6.51,   100: 6.04},
    2000:  {10: 28.5,  15: 39.7,  20: 40.6,  30: 31.0,  40: 22.8,  50: 17.6,  60: 14.2,  70: 12.0,   80: 10.5,   90: 9.43,   100: 8.62},
    2500:  {10: 30.3,  15: 45.9,  20: 51.6,  30: 44.3,  40: 33.8,  50: 26.4,  60: 21.5,  70: 18.1,   80: 15.7,   90: 13.9,   100: 12.6},
    3150:  {10: 31.9,  15: 51.5,  20: 63.1,  30: 61.7,  40: 50.1,  50: 40.1,  60: 32.8,  70: 27.7,   80: 24.0,   90: 21.2,   100: 19.1},
    4000:  {10: 33.6,  15: 56.3,  20: 73.9,  30: 83.0,  40: 73.0,  50: 60.7,  60: 50.6,  70: 43.1,   80: 37.3,   90: 33.0,   100: 29.6},
    5000:  {10: 35.4,  15: 60.2,  20: 82.8,  30: 105.0, 40: 100.0, 50: 87.4,  60: 74.9,  70: 64.5,   80: 56.4,   90: 50.0,   100: 44.9},
    6300:  {10: 38.0,  15: 64.3,  20: 90.9,  30: 127.0, 40: 133.0, 50: 124.0, 60: 110.0, 70: 96.7,   80: 85.6,   90: 76.4,   100: 68.9},
    8000:  {10: 42.0,  15: 69.3,  20: 98.9,  30: 148.0, 40: 170.0, 50: 169.0, 60: 158.0, 70: 144.0,  80: 130.0,  90: 117.0,  100: 107.0},
    10000: {10: 47.7,  15: 75.7,  20: 107.0, 30: 167.0, 40: 205.0, 50: 218.0, 60: 214.0, 70: 201.0,  80: 186.0,  90: 172.0,  100: 158.0},
}






def _get_m(etc_in, etc_out, distance):
    return -math.log(etc_out / etc_in) / distance


def _m_per_m_from_apply(temperature, frequency, relative_humidity_percent,
                         atmospheric_pressure=101325.0, distance=1.0):
    # apply_pure_tone_attenuation with a single time bin at distance=0 (etc_in)
    # and one at `distance` (etc_out), sampling_rate and speed chosen so that
    # time * speed_of_sound_ms == distance.
    etc_in = 1.0
    etc = [etc_in, etc_in]
    out = mi.acoustic.apply_pure_tone_attenuation(
        etc, 1.0, distance, temperature, [frequency],
        relative_humidity_percent / 100.0, atmospheric_pressure)
    etc_out = out[1]
    return _get_m(etc_in, etc_out, distance)


# The reference tables above give the attenuation coefficient in dB/km
def _db_per_km_to_m_per_m(db_per_km):
    return db_per_km / 1000.0 / (10.0 * math.log10(math.e))


REFERENCE_CASES = [
    (-20.0, ABSORPTION_DATA_MINUS_20C),
    (5.0, ABSORPTION_DATA_5C),
    (25.0, ABSORPTION_DATA_25C),
]


def test01_hasattr_acoustic(variants_all_acoustic):
    assert hasattr(mi, "acoustic")


@pytest.mark.parametrize("temperature,table", REFERENCE_CASES)
def test02_energy_attenuation_coefficient_matches_reference(variants_all_acoustic, temperature, table):
    # spot-check a handful of frequency/humidity combinations per temperature
    # category against the reference tables above (rel. tolerance accounts
    # for the tables' own rounding to 3 significant digits). See the note
    # above the tables: these are regression values computed from our own
    # implementation, not the ISO 9613-1 table itself.
    frequencies = (50, 63, 250, 1000, 4000, 6300, 10000)
    humidities = (10, 20, 30, 50, 70, 100)

    for frequency in frequencies:
        for humidity in humidities:
            expected_db_per_km = table[frequency][humidity]
            expected_m = _db_per_km_to_m_per_m(expected_db_per_km)
            got_m = _m_per_m_from_apply(temperature, frequency, humidity)
            assert got_m == pytest.approx(expected_m, rel=0.015) #1,5% relative tolerance


def test03_apply_pure_tone_attenuation_direct_call(variants_all_acoustic):
    # simple end-to-end sanity check: energy must decay with distance and
    # higher frequencies must attenuate more than lower ones
    n_time_bins = 4
    frequencies = [500.0, 4000.0]
    etc = [1.0] * (n_time_bins * len(frequencies))

    out = mi.acoustic.apply_pure_tone_attenuation(
        etc, sampling_rate=10.0, speed_of_sound_ms=343.0,
        temperature=20.0, frequencies=frequencies,
        relative_humidity=0.5, atmospheric_pressure=101325.0)

    out_low = out[0::2]
    out_high = out[1::2]

    assert out_low[0] == pytest.approx(1.0)
    assert out_high[0] == pytest.approx(1.0)
    for t in range(1, n_time_bins):
        assert out_low[t] < out_low[t - 1]
        assert out_high[t] < out_high[t - 1]
        assert out_high[t] < out_low[t]


def test04_etc_size_not_multiple_of_frequencies_raises(variants_all_acoustic):
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0, 1.0, 1.0], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=20.0, frequencies=[1000.0, 2000.0],
            relative_humidity=0.5, atmospheric_pressure=101325.0)


def test05_empty_frequencies_raises(variants_all_acoustic):
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=20.0, frequencies=[],
            relative_humidity=0.5, atmospheric_pressure=101325.0)


def test06_temperature_too_low_raises(variants_all_acoustic):
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=-100.0, frequencies=[1000.0],
            relative_humidity=0.5, atmospheric_pressure=101325.0)


def test07_frequency_too_low_raises(variants_all_acoustic):
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=20.0, frequencies=[10.0],
            relative_humidity=0.5, atmospheric_pressure=101325.0)


def test08_atmospheric_pressure_too_high_raises(variants_all_acoustic):
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=20.0, frequencies=[1000.0],
            relative_humidity=0.5, atmospheric_pressure=250000.0)


def test09_frequency_to_pressure_ratio_out_of_range_raises(variants_all_acoustic):
    # ratio below 4e-4 Hz/Pa
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=20.0, frequencies=[50.0],
            relative_humidity=0.5, atmospheric_pressure=150000.0)
    # ratio above 10 Hz/Pa
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0], sampling_rate=10.0, speed_of_sound_ms=343.0,
            temperature=20.0, frequencies=[10000.0],
            relative_humidity=0.5, atmospheric_pressure=500.0)


def test10_distance_too_large_raises(variants_all_acoustic):
    # time bin 1 is at 1s * 20000 m/s = 20 km > the 10 km limit
    with pytest.raises(Exception):
        mi.acoustic.apply_pure_tone_attenuation(
            etc=[1.0, 1.0], sampling_rate=1.0, speed_of_sound_ms=20000.0,
            temperature=20.0, frequencies=[1000.0],
            relative_humidity=0.5, atmospheric_pressure=101325.0,
            n_time_bins=2, n_frequencies=1)

